### ISSUE TITLE
L5: Populate doesn't work if field has spaces in it (example)

### ISSUE THREAD

**Issue by that0n3guy** [formers/former#451]
Here is an example:

```
Former::text('FirstName'); // this will prepopulate
Former::text('First Name')->name('firstname'); // this will NOT prepopulate
Former::text('First Name')->id('firstname'); // this will NOT prepopulate
```

**Comment by that0n3guy** [comment]
It looks like this is because the posted data from a form will change the key to have an underscore.  

For example: 

My form has field `Former::text('First Name');`... this will post as `First_Name`=>'valuehere'`.  So my array which is full of posted data (like from validation) doesn't match up because `First_Name` does not equal `First Name`;

Still a bug I think.

**Comment by claar** [comment]
The first argument to `text()`, `select()`, etc. is the field name, not the field label. If you want to set the label, you should use `text('myname')->label('My Name')`.

Since the HTML [name attribute doesn't allow spaces](http://stackoverflow.com/questions/5688200/can-i-use-white-spaces-in-the-name-attribute-of-an-html-element), I think this is a won't-fix.

I agree that the current behavior doesn't make a lot of sense, but specifying a name with spaces is non-sensical as well, so I'm not inclined to think it matters.

**Comment by that0n3guy** [comment]
It would be nice if `Former::text('First Name');` simply acted like `Former::text('FirstName').label('First Name');`  Since the name attribute cant have spaces in it.

**Comment by claar** [comment]
I tend toward the Drupal philosophy of "don't babysit broken code", myself. I do think the documentation could be vastly improved, however.
