### ISSUE TITLE
Make populate() work with bootstrap-datepicker

### ISSUE THREAD

**Issue by svengit** [formers/former#476]
When using bootstrap-datepicker (https://github.com/eternicode/bootstrap-datepicker) together with former you run into problems.

Here is some Laravel 4 example code that reproduces the issue:

```
{{ Former::populate( MyObject::find( $obj->id ) ) }}
{{ Former::text( 'expires_at' )->label( 'Expiry:' )->class( 'datepicker' )->data_provide( 'datepicker' )->data_date_format(    >> 'yyyy-mm-dd' )->data_date_autoclose( '1' ) }}
```

This leads to a lot of 'NaN' values in the datepicker and makes it practically unusable. I tried resetting it with its provides JS functions, but that doesn't work either. 
The correct way to set the date would be:

```
 <script>
     $(document).ready(function() {
     $('.datepicker').datepicker('update', '{{ $expires_at->format( 'Y-m-d' ) }}' );
      } );
 </script> 
```

So one option would be to add an 'exclude' parameter to the populate() function and use the JS to set the date by hand...

**Comment by claar** [comment]
Closing old issues, please reopen with more details if still relevant.

**Comment by svengit** [comment]
So you are closing it after 2 years because it is 'old', not because you fixed it? Way to go.

**Comment by claar** [comment]
Hi @svengit,

Like most open source projects, we have limited resources to investigate issues. It's usually not efficient to investigate 2-year-old issues that relate to a specific 3rd party library, reported by a single user.

eternicode/bootstrap-datepicker has had 532 commits since May 18th, 2015:

```
git clone git@github.com:uxsolutions/bootstrap-datepicker.git
git log --since="2015-18-00T00:00:00-06:00" --format=oneline | wc -l
```

In my experience, closing old issues like this one is the most efficient manner to communicate to the reporter than no further resources will be devoted to the problem unless we hear that the issue still exists and additional details are provided.

Sadly, at times entitled users will simply respond with sarcastic and hurtful statements rather than participating collaboratively in the resolution of their issues, though facilitated by good-intentioned volunteers. Such is the nature of open source projects, unfortunately. But we cheerfully continue on making the best of our limited resources.
