### ISSUE TITLE
Does this work with form requests?

### ISSUE THREAD

**Issue by maxi032** [formers/former#526]
Is this package working with form requests or this is kind of redundant?

**Comment by claar** [comment]
Hey @maxi032 -- I don't understand the question.

**Comment by maxi032** [comment]
This is a form request in Laravel5: https://laravel.com/docs/master/validation#form-request-validation 
Can I use Former with validations rules specified in the form request or do I need to use a validation object and do if($validation->fails()) ...

**Comment by claar** [comment]
Ah, thanks for the clarification @maxi032.

Former's job is to print out HTML for form elements; it doesn't get involved with server-side validation of forms. So the short answer is "Yes", Former should work fine with any type of server side validation, including form requests. If you find otherwise, please open an issue! Thanks!
