### ISSUE TITLE
How to use as a  standalone PHP 

### ISSUE THREAD

**Issue by anjalitechn** [formers/former#611]
When using as standalone application without laravel It is giving error
Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Illuminate\Routing\RouteCollectionInterface] is not instantiable while building [Illuminate\Routing\UrlGenerator]

**Comment by anjalitechn** [comment]
hi @claar 
can you please help.

**Comment by claar** [comment]
Hi @anjalitechn - I'm sorry, but I'm not able to offer general tech support for this package at this time. If you're able to get to the root of the problem, I'd be happy to review any Pull Request you'd like to create to solve this issue for the community.

**Comment by aleemb** [comment]
@claar I found the quick fix is as follows, however, I am not familiar with the framework to do this proper. The fix that works for me is inside `FormerServicesProvider.php` I add the following in `bindCoreClasses` under the `Core Classes` comment:

```php
		$app->bindIf(
			\Illuminate\Routing\RouteCollectionInterface::class,
			\Illuminate\Routing\RouteCollection::class
		);
```

Trying `$app->bindIf('routing', \Illuminate\Routing\RouteCollection::class);` didn't work, however.

Hope this can be fixed in the repo so Former can once again be used outside of Laravel. This is the only thing preventing that use-case right now for anyone using it outside of Laravel, myself included.
